openapi: 3.0.0
info:
  title: PLANT APP API
  version: 1.0.0
servers:
  - url: https://plantapp-2mp9.onrender.com/api/v1
    variables: {}

paths:
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login user
      operationId: LoginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginUserRequest"
            example:
              email: mama@gmail.com
              password: shewareg
      responses:
        "200":
          description: Logged in
          content:
            application/json:
              example:
                {
                  "user":
                    { "name": "Mama", "userId": "68958ea9316675518a96b222" },
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODk1OGVhOTMxNjY3NTUxOGE5NmI0MzkiLCJuYW1lIjoiU3R1IiwiaWF0IjoxNzU1MDQ2Mjc1LCJleHAiOjE3NTc2MzgyNzV9.-WmPybA09SJ0I5feFY7rgFlaEPVBBrC-aomp1QwrVBv",
                }
      security: []

  /auth/register:
    post:
      tags:
        - Auth
      summary: Register user
      operationId: RegisterUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterUserRequest"
            example:
              name: elinatal
              email: baby@gmail.com
              password: timotios
      responses:
        "201":
          description: Registered
          content:
            application/json:
              example:
                {
                  "user":
                    {
                      "name": "elinatal",
                      "userId": "68958ea9316675518a96b234",
                    },
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODk1OGVhOTMxNjY3NTUxOGE5NmI0MzkiLCJuYW1lIjoiU3R1IiwiaWF0IjoxNzU1MDQ2Mjc1LCJleHAiOjE3NTc2MzgyNzV9.-WmPybA09SJ0I5feFY7rgFlaEPVBBrC-aomp1QwrfEv",
                }
      security: []

  /plants:
    post:
      tags:
        - Plants
      summary: Create plant entry
      operationId: CreatePlantEntry
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePlantEntryRequest"
            example:
              name: "palm tree"
              imageURL: "www.coastal-trees.com"
              notes: "It has coconuts"
              location: "The beach"
        required: true
      responses:
        "201":
          description: "Successful Response"
          content:
            application/json:
              example:
                {
                  "plant":
                    {
                      "name": "palm tree",
                      "imageURL": "www.coastal-trees.com",
                      "notes": "It has coconuts",
                      "location": "The beach",
                      "createdBy": "68958ea9316675518a96b420",
                      "_id": "689bd41309dc34a1f4082111",
                      "createdAt": "2025-08-12T23:53:55.317Z",
                      "updatedAt": "2025-08-12T23:53:55.317Z",
                      "__v": 0,
                    },
                }
          headers: {}
      deprecated: false

    get:
      tags:
        - Plants
      summary: Get all plant entries
      operationId: GetAllPlantEntries
      parameters: []
      responses:
        "200":
          description: "Successful Response"
          content:
            application/json:
              example:
                {
                  "plants":
                    [
                      {
                        "_id": "68979fc17f6eddd77c76db3s",
                        "name": "rose",
                        "createdBy": "68958ea9316675518a96b421",
                        "imageURL": "www.rose-pic.com",
                        "notes": "This rose is beautiful!",
                        "location": "222 N Smith Ln",
                        "createdAt": "2025-08-09T19:21:37.403Z",
                        "updatedAt": "2025-08-09T19:21:37.403Z",
                        "__v": 0,
                      },
                      {
                        "_id": "6897a1d5b6dc952f78612efr",
                        "name": "cactus",
                        "imageURL": "www.crazy-cactus-img.com",
                        "notes": "This was growing in my backyard",
                        "location": "my backyard",
                        "createdBy": "68958ea9316675518a96b476",
                        "createdAt": "2025-08-09T19:30:29.924Z",
                        "updatedAt": "2025-08-09T19:30:29.924Z",
                        "__v": 0,
                      },
                    ],
                  "count": 2,
                }
          headers: {}
      deprecated: false

  /plants/{plantID}:
    parameters:
      - in: path
        name: plantID
        schema:
          type: string
          example: 68991aa9444dc94a77ead824
        required: true
        description: The plant ID

    get:
      tags:
        - Plants
      summary: Get single plant entry
      operationId: GetSinglePlantEntry
      parameters: []
      responses:
        "200":
          description: "Successful Response"
          content:
            application/json:
              example:
                {
                  "plant":
                    {
                      "_id": "68991aa9444dc94a77ead848",
                      "name": "oak tree",
                      "imageURL": "www.oaktrees.net",
                      "notes": "Massive oak tree I saw!",
                      "location": "near the forest south of town",
                      "createdBy": "68958ea9316675518a96b439",
                      "createdAt": "2025-08-10T22:18:17.679Z",
                      "updatedAt": "2025-08-10T23:42:03.742Z",
                      "__v": 0,
                    },
                }
          headers: {}
      deprecated: false

    patch:
      tags:
        - Plants
      summary: Update plant entry
      operationId: UpdatePlantEntry
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdatePlantEntryRequest"
            example:
              name: "oak tree"
              imageURL: "www.oaktrees.net"
              notes: "Massive oak tree I saw!"
              location: "near the forest south of town"
        required: true
      responses:
        "200":
          description: "Successful Response"
          content:
            application/json:
              example:
                {
                  "plant":
                    {
                      "_id": "68991aa9444dc94a77ead848",
                      "name": "oak tree",
                      "imageURL": "www.oaktrees.net",
                      "notes": "Massive oak tree I saw!",
                      "location": "near the forest south of town",
                      "createdBy": "68958ea9316675518a96b439",
                      "createdAt": "2025-08-10T22:18:17.679Z",
                      "updatedAt": "2025-08-13T00:28:09.856Z",
                      "__v": 0,
                    },
                }
          headers: {}
      deprecated: false

    delete:
      tags:
        - Plants
      summary: Delete plant entry
      operationId: DeleteExercise
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              example: { msg: "The entry was successfully deleted" }
          headers: {}
      deprecated: false

  /identifyPlants:
    post:
      tags:
        - Identify Plants
      summary: Identify plant by image
      operationId: identifyPlants
      parameters: []
      requestBody:
        description: ""
        content:
          multipart/form-data:
            schema:
              type: object
              $ref: "#/components/schemas/IdentifyPlantsRequest"
              properties:
                images:
                  type: string
                  format: binary
        required: true
      responses:
        "200":
          description: "Successful Response"
          content:
            application/json:
              example:
                {
                  "data":
                    [
                      {
                        "id": 2498,
                        "common_name": "Venus fly trap",
                        "scientific_name": ["Dionaea muscipula"],
                        "other_name": [],
                        "family": "Droseraceae",
                        "hybrid": null,
                        "authority": null,
                        "subspecies": null,
                        "cultivar": null,
                        "variety": null,
                        "species_epithet": "muscipula",
                        "genus": "Dionaea",
                        "default_image":
                          {
                            "license": 45,
                            "license_name": "Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)",
                            "license_url": "https://creativecommons.org/licenses/by-sa/3.0/deed.en",
                            "original_url": "https://perenual.com/storage/species_image/2498_dionaea_muscipula/og/2560px-Dionaea_muscipula2C_exhibition_in_Botanical_garden_Brno.jpg",
                            "regular_url": "https://perenual.com/storage/species_image/2498_dionaea_muscipula/regular/2560px-Dionaea_muscipula2C_exhibition_in_Botanical_garden_Brno.jpg",
                            "medium_url": "https://perenual.com/storage/species_image/2498_dionaea_muscipula/medium/2560px-Dionaea_muscipula2C_exhibition_in_Botanical_garden_Brno.jpg",
                            "small_url": "https://perenual.com/storage/species_image/2498_dionaea_muscipula/small/2560px-Dionaea_muscipula2C_exhibition_in_Botanical_garden_Brno.jpg",
                            "thumbnail": "https://perenual.com/storage/species_image/2498_dionaea_muscipula/thumbnail/2560px-Dionaea_muscipula2C_exhibition_in_Botanical_garden_Brno.jpg",
                          },
                      },
                    ],
                  "length": 1,
                }
          headers: {}
      deprecated: false

  /identifyPlants/{plantID}:
    parameters:
      - in: path
        name: plantID
        schema:
          type: string
          example: 502
        required: true
        description: The plant ID

    get:
      tags:
        - Identify Plants
      summary: Get single plant data
      operationId: identifySinglePlant
      parameters: []
      responses:
        "200":
          description: "Successful Response"
          content:
            application/json:
              example:
                {
                  "data":
                    {
                      "id": 502,
                      "common_name": "hot water plant",
                      "scientific_name": ["Achimenes (group)"],
                      "other_name": [],
                      "family": "Gesneriaceae",
                      "hybrid": null,
                      "authority": null,
                      "subspecies": null,
                      "cultivar": null,
                      "variety": null,
                      "species_epithet": "(group)",
                      "genus": "Achimenes",
                      "origin":
                        [
                          "Mexico",
                          "Guatemala",
                          "Honduras",
                          "Costa Rica",
                          "Panama",
                          "Colombia",
                          "Venezuela",
                          "Ecuador",
                          "Peru",
                        ],
                      "type": "Herbs",
                      "dimensions":
                        [
                          {
                            "type": null,
                            "min_value": 1,
                            "max_value": 2,
                            "unit": "feet",
                          },
                        ],
                      "cycle": "Herbaceous Perennial",
                      "attracts": [],
                      "propagation":
                        [
                          "Division",
                          "Cutting",
                          "Seed Propagation",
                          "Tissue Culture",
                        ],
                      "hardiness": { "min": "10", "max": "11" },
                      "hardiness_location":
                        {
                          "full_url": "https://perenual.com/api/hardiness-map?species_id=502&size=og&key=sk-7wRB68a4e4efc60fe11920",
                          "full_iframe": "<iframe frameborder=0 scrolling=yes seamless=seamless width=1000 height=550 style='margin:auto;' src='https://perenual.com/api/hardiness-map?species_id=502&size=og&key=sk-7wRB68a4e4efc60fe11920'></iframe>",
                        },
                      "watering": "Average",
                      "watering_general_benchmark":
                        { "value": null, "unit": "days" },
                      "plant_anatomy": [],
                      "sunlight": ["part shade"],
                      "pruning_month":
                        [
                          "May",
                          "March",
                          "April",
                          "May",
                          "June",
                          "July",
                          "August",
                          "September",
                        ],
                      "pruning_count": [],
                      "seeds": false,
                      "maintenance": "Moderate",
                      "care_guides": "http://perenual.com/api/species-care-guide-list?species_id=502&key=sk-7wRB68a4e4efc60fe11920",
                      "soil": [],
                      "growth_rate": "Low",
                      "drought_tolerant": false,
                      "salt_tolerant": false,
                      "thorny": false,
                      "invasive": false,
                      "tropical": false,
                      "indoor": true,
                      "care_level": "Medium",
                      "pest_susceptibility": [],
                      "flowers": true,
                      "flowering_season": null,
                      "cones": false,
                      "fruits": false,
                      "edible_fruit": false,
                      "harvest_season": null,
                      "leaf": true,
                      "edible_leaf": false,
                      "cuisine": false,
                      "medicinal": false,
                      "poisonous_to_humans": false,
                      "poisonous_to_pets": false,
                      "description": "The Hot Water Plant is an awesome choice of species for any avid gardener. It is a perennial plant, with unique and exotic blooms in a variety of shapes and colors, that can be grown indoors or outdoors. These plants are incredibly adaptive, thriving in all sorts of climates, from warm rainforest environments to cool temperate locations. In order to grow them, simply fill any container with water, place the root-ball into it, and enjoy the beautiful flowers that emerge for months. Hot Water Plants are also great for propagating and are incredibly low-maintenance, surviving both drought and short-term flooding easily. A truly amazing species that anyone can grow.",
                      "default_image": null,
                      "other_images": "Upgrade Plan To Supreme For Access https://perenual.com/subscription-api-pricing. Im sorry",
                      "xWateringQuality": "Upgrade Plan To Supreme For Access https://perenual.com/subscription-api-pricing. Im sorry",
                      "xWateringPeriod": "Upgrade Plan To Supreme For Access https://perenual.com/subscription-api-pricing. Im sorry",
                      "xWateringAvgVolumeRequirement": "Upgrade Plan To Supreme For Access https://perenual.com/subscription-api-pricing. Im sorry",
                      "xWateringDepthRequirement": "Upgrade Plan To Supreme For Access https://perenual.com/subscription-api-pricing. Im sorry",
                      "xWateringBasedTemperature": "Upgrade Plan To Supreme For Access https://perenual.com/subscription-api-pricing. Im sorry",
                      "xWateringPhLevel": "Upgrade Plan To Supreme For Access https://perenual.com/subscription-api-pricing. Im sorry",
                      "xSunlightDuration": "Upgrade Plan To Supreme For Access https://perenual.com/subscription-api-pricing. Im sorry",
                      "xTemperatureTolence": "Upgrade Plan To Supreme For Access https://perenual.com/subscription-api-pricing. Im sorry",
                      "xPlantSpacingRequirement": "Upgrade Plan To Supreme For Access https://perenual.com/subscription-api-pricing. Im sorry",
                    },
                }
          headers: {}
      deprecated: false

components:
  schemas:
    RegisterUserRequest:
      title: RegisterUserRequest
      required:
        - name
        - email
        - password
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      example:
        name: bob
        email: bob@gmail.com
        password: secret

    LoginUserRequest:
      title: LoginUserRequest
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: susan@gmail.com
        password: secret

    CreatePlantEntryRequest:
      title: CreatePlantEntryRequest
      required:
        - name
      type: object
      properties:
        name:
          type: string
        imageURL:
          type: string
        notes:
          type: string
        location:
          type: string
      example:
        name: oak tree
        imageURL: www.oaktrees.net
        notes: Massive oak tree I saw!
        location: near the forest south of town

    UpdatePlantEntryRequest:
      title: UpdatePlantEntryRequest
      type: object
      properties:
        name:
          type: string
        imageURL:
          type: string
        notes:
          type: string
        location:
          type: string
      example:
        name: oak tree
        imageURL: www.plant-life.com
        notes: Massive oak tree I saw!
        location: 231 Easy Street

    IdentifyPlantsRequest:
      title: IdentifyPlantsRequest
      type: object
      properties:
        image:
          type: string
          format: binary

  securitySchemes:
    httpBearer:
      type: http
      scheme: bearer

security:
  - httpBearer: []

tags:
  - name: Auth
    description: User authentication with email & password
  - name: Plants
    description: Logged in user operation for creating and storing plant data
